# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45275bc62f647f0d94997d52da2803915f1c64aa3403edd8fcfaef04b6a9f2fa9abe001adecc8891eeda0430b5b0050ee55a7074df15bc5fa0cb72e11e864e8c

test:
  secret_key_base: 121ae954be1566d80cb35d66dc76c24e2f1996700553c54d509dc7227cdf94cce9e4bfe07252f512cb68ecc67b8f418ddd45efa05fa734f1c9bc87e483fd9693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
